DWAPlannerROS:
  max_vel_x: 0.45
  min_vel_x: -0.05
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 6.3
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
#  sim_time: 1.5
# vx_samples: 20
#  vy_samples: 0
#  vth_samples: 40
#  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.5
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
#  oscillation_reset_dist: 0.05

# Debugging
#  publish_traj_pc : true
#  publish_cost_grid_pc: true