shutdown_costmaps: false
#controller_frequency: 10.0
#planner_patience: 3.0
#controller_patience: 5.0
#conservative_reset_dist: 3.0
planner_frequency: 1.0
#oscillation_timeout: 5.0
oscillation_distance: 0.5
recovery_behavior_enabled: true
max_planning_retries: 40