global_costmap: {
  global_frame: robot1/map,
  robot_base_frame: robot1/base_link,
  observation_sources: scan,
  scan: {
    sensor_frame: robot1/hokuyo_link, 
    data_type: LaserScan, 
    topic: scan, 
    marking: true, 
    clearing: true
  },
  obstacle_layer: {
    observation_sources: scan,
    scan: {
      sensor_frame: robot1/hokuyo_link, 
      data_type: LaserScan, 
      topic: scan, 
      marking: true, 
      clearing: true
    },
  }
}

local_costmap: {
  global_frame: robot1/map,
  robot_base_frame: robot1/base_link,
  observation_sources: scan,
  scan: {
    sensor_frame: robot1/hokuyo_link, 
    data_type: LaserScan, 
    topic: scan, 
    marking: true, 
    clearing: true
  },
  obstacle_layer: {
    observation_sources: scan,
    scan: {
      sensor_frame: robot1/hokuyo_link, 
      data_type: LaserScan, 
      topic: scan, 
      marking: true, 
      clearing: true
    },
  }
}